### PR TITLE
Add CI project configuration

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Depends-On: https://github.com/ansible/zuul-jobs/pull/2/

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
Depends-on doesn't work as zuul configuration files can't be merged (#2 uses .zuul.d and #3 uses zuul.yaml).   I squashed #2 and #3 in PR #4. let's merge this one instead.

**Pull request closed without merging**
